export const TemplateValues = [
  'Azure Blob Storage trigger',
  'Durable Functions activity',
  'Durable Functions entity',
  'Durable Functions Entity HTTP starter',
  'Durable Functions HTTP starter',
  'Durable Functions orchestrator',
  'Azure Event Grid trigger',
  'Azure Event Hub trigger',
  'HTTP trigger',
  'IoT Hub (Event Hub)',
  'Kafka output',
  'Kafka trigger',
  'Azure Queue Storage trigger',
  'RabbitMQ trigger',
  'SendGrid',
  'Azure Service Bus Queue trigger',
  'Azure Service Bus Topic trigger',
  'SignalR negotiate HTTP trigger',
  'Timer trigger',
] as const;
