name: Full CI/CD
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  release:
    types: [created]

permissions:
  contents: read
  id-token: write

jobs:
  Release:
    name: Build, test and release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          registry-url: "https://registry.npmjs.org"
      - name: Install func CLI 🛠️
        run: npm i -g azure-functions-core-tools@4 --unsafe-perm true
      - name: Install dependencies 🛠️
        run: npm ci
      - name: Build project 👷‍♂️🏗️
        run: npm run build:all
      - name: Unit Testing 🧪
        run: npm run test:all
      - name: E2E Testing 🧪
        run: npm run e2e:all
      - name: Publish package on NPM 📦
        if: ${{ github.event_name == 'release' }}
        run: npm publish dist/packages/func --access=public
